{
  try {
    return Boolean.valueOf(prolonger.call());
  }
 catch (  Exception e) {
    throw new RuntimeException("Prolonger call finished with error",e);
  }
}
