{
  try {
    testee.throwChainedConnectException();
  }
 catch (  KettleRepositoryLostException krle) {
    Throwable found=krle;
    while (found != null) {
      if (connectException.equals(found)) {
        break;
      }
      found=found.getCause();
    }
    assertNotNull("Should have found the original ConnectException");
  }
catch (  Throwable other) {
    fail("Should not catch something other than KettleRepositoryLostException");
  }
}
